config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :posts do #Allow functionality for users
  	member do
  		get "like", to: "posts#upvote"
  		get "dislike", to: "posts#downvote"
  	end
  	resources :comments
  end

authenticated do
  root :to => 'posts#userindex', as: :authenticated #If user is logged in, make userindex page the home page
end

  root 'posts#index' # Else make index page home page for non logged in users



  get '/user/:id' => 'posts#profile' #link to user profiles, defined by user id (username)

  get 'explore' => 'posts#explore' #Link to explore page

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post #is associated with post
  belongs_to :user #is associated with the comment poster
end

app/models/post.rb
class Post < ActiveRecord::Base
	
	acts_as_votable
	belongs_to :user #Post belongs to user
	validates :user_id, presence: true #Post has to associate to user id
	has_attached_file :image #Post can have image
 	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/ #Image needs to be a valid image file
 	validates :description, presence: true #Posts has to have description
 	has_many :comments #Post can have many comments
 	has_attached_file :avatar #User profile photo is attached to post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    validates :name, uniqueness: true #username must be unique

        has_many :posts #User has many posts
        has_many :comments #user has many comments

        has_attached_file :avatar, :default_url => "/images/profile.png" #User has a profile picture
  		validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/ #Image needs to be a valid image file
  		
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller? #Specifies Devise login

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) } #Allow stated paramaters to be used for sign up
  	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :avatar) } #Allow stated paramaters to edited
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :authenticate_user! #Before function, authenticate user

	def create
		@post = Post.find(params[:post_id]) #Define user by current ID
		@comment = Comment.create(params[:comment].permit(:content)) #Allow comment to be created
		@comment.user_id = current_user.id #Link comment to user by ID
		@comment.post_id = @post.id #Link comment to user by User ID and Post IS

		if @comment.save
			redirect_to post_path(@post) #Once SAved, re-direct to comment
		else
			render 'new' #Else render a new comment
	end
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote, :avatar] #Allow stated paramaters to be posted
	before_action :authenticate_user!, except: [:index, :explore, :show] #Allow these pages to be accessed by non logged in user, otherwise re-direct them to log in

	def userindex
		@posts = Post.all.order("created_at DESC") #Display all posts created in descending order
	end

	def profile
		@posts = Post.all.order("created_at DESC").where("user_id = ?", User.find_by_name(params[:id]).id) #Display all posts created in descending order associated with user

	    if (User.find_by_name(params[:id])) #Define URL by username
	      @username = params[:id]

	    else
	      redirect_to root_path, :notice => "User Not Found!" #If not found, display notice
	    end 

	end

	def show
		@comments = Comment.where(post_id: @post) #Allow comments on posts

	end

	def new
		@post = current_user.posts.build #Associate created post with user currently logged in
	end

	def create
		@post = current_user.posts.build(post_params) #Associate created post with user currently logged in

		if @post.save
			redirect_to @post #Once post is saved, re-direct to post
		else
			render 'new' #Otherwise render new post
		end
	end

	def edit
	end

	def update
		if @post.update(post_params) #Update posts
			redirect_to @post #Once edited, re-direct to post
		else
			render 'edit' #else open edit page
		end
	end

	def destroy
		@post.destroy #Destroy post
		redirect_to root_path #Re-direct back to home
	end

	def upvote
		@post.upvote_by current_user #Allow users to upvote post
		redirect_to :back
	end

	def downvote
		@post.downvote_by current_user #Allow users to downvote post
		redirect_to :back
	end

	private

	def find_post
		@post = Post.find(params[:id]) #Find posts by posts associated with :id (username)
	end

	def post_params
		params.require(:post).permit(:title, :image, :description, :avatar) #Allow stated paramaters to be posted
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<div class="post">
	<%= simple_form_for([@post, @post.comments.build]) do |f| %> <!-- Create comment form for post -->

		<%= f.input :content, label: "Write a Comment" %> <!-- Form to write comment -->

		<%= f.button :submit, class: "comment-button" %> <!-- Submit comment -->
	<% end %>
</div>

app/views/layouts/_bottom.html.erb
<% !if user_signed_in? %> <!-- If user is signed in render below naviagtion-->
	<%= render '/layouts/bottom_user' %>
<% else %>
	<%= render '/layouts/bottom_guest' %>
<% end %>

app/views/layouts/_bottom_guest.html.erb
	  <div class="bottom-nav"> <!-- Guest Navigation-->

			
			<!--Nav Buttn Menu -->
			
			<div id="menu-button">
				<%= image_tag("menu.png", :alt => "Menu Button",  :class => "button-img") %>
			</div>

			<a href="#">
				<div id="nav-button">
					<%= image_tag("message.png", :alt => "Message Button",  :class => "button-img") %>
				</div>				
			</a>
				
			<a href="/">
				<div id="nav-button">
					<%= image_tag("home.png", :alt => "Home Button",  :class => "button-img") %>
				</div>
				
			</a>
				
			<a href="explore">
				<div id="nav-button">
					<%= image_tag("local.png", :alt => "Explore Button",  :class => "button-img") %>
				</div>
				
			</a>
				
			<a href="/users/sign_in">	
				<div id="nav-button">
					<%= image_tag("profile.png", :alt => "Profile Button",  :class => "button-img") %>
				</div>
				
			</a>
			
	  </div>

app/views/layouts/_bottom_user.html.erb
	<!-- User Navigation-->

	  <div class="bottom-nav">

			
			<!--Nav Buttn Menu -->
			
			<div id="menu-button">
				<%= image_tag("menu.png", :alt => "Menu Button",  :class => "button-img") %>
			</div>
			
			
			<a href="#">
				<div id="nav-button">
					<%= image_tag("message.png", :alt => "Message Button",  :class => "button-img") %>
				</div>				
			</a>
				
			<a href="/">
				<div id="nav-button">
					<%= image_tag("home.png", :alt => "Home Button",  :class => "button-img") %>
				</div>
				
			</a>
				
			<a href="/explore">
				<div id="nav-button">
					<%= image_tag("local.png", :alt => "Explore Button",  :class => "button-img") %>
				</div>
				
			</a>
				
			<a href="/user/<%= current_user.name %>">	
				<div id="nav-button">
					<%= image_tag("profile.png", :alt => "Profile Button",  :class => "button-img") %>
				</div>
				
			</a>
			
	  </div>

app/views/layouts/_nav.html.erb
<% !if user_signed_in? %> <!-- If user is not signed in render below naviagtion-->
	<%= render '/layouts/nav_user' %>
<% else %>
	<%= render '/layouts/nav_guest' %>
<% end %>

app/views/layouts/_nav_guest.html.erb
<!-- Guest Navigation-->


  
	<header>
		<a href="javascript:history.back()">
			<div id="top-nav-button-left">
				<%= image_tag("back3.png", :alt => "Message Button",  :class => "button-img") %>
			</div>
		</a>

		<a href="#">
			<input type="text" class="mainsearch" placeholder="Search..." >
		</a>

	</header>
	  
	  
  
  <!--Slide Out Menu -->
	  <nav>
		<ul>
			<li>
				<input type="text" class="navsearch" value="Search...">
			</li>
			
			<a href="#">
				<li class="user-prof-nav">
					<%= image_tag("profile.png", :alt => "User Profile",  :class => "nav-prof-photo") %>
					<p class="nav-prof-name">Guest</p>
				</li>
			</a>
			  
			<a href="/">
				<li>				
					<%= image_tag("home.png", :alt => "Home",  :class => "slide-button") %>
					<p class="nav-prof-name">Home</p>
				</li>
			</a>				
			
			<a href="/explore">
				<li>
					<%= image_tag("local.png", :alt => "Local Area",  :class => "slide-button") %>
					<p class="nav-prof-name">Local Area</p>
				</li>
			</a>
			
			<a href="#">
				<li>
					<%= image_tag("message.png", :alt => "Messages",  :class => "slide-button") %>
					<p class="nav-prof-name">Messages</p>
				</li>
			</a>

			<a href="#">
				<li>
					<%= image_tag("faq.png", :alt => "FAQ",  :class => "slide-button") %>
					<p class="nav-prof-name">FAQ</p>
				</li>
			</a>

			<a href="#">
				<li>
					<%= image_tag("settings.png", :alt => "Settings",  :class => "slide-button") %>
					<p class="nav-prof-name">Settings</p>
			    </li>		  
			</a>			
		</ul>
		<div class="nav-bottom">
			<%= link_to('Log In', new_user_session_path) %><br><br>
			<%= link_to('Sign Up', new_user_registration_path) %>
		</div>
	  </nav>

app/views/layouts/_nav_user.html.erb
<!-- User Navigation-->


  
	<header>
		<a href="javascript:history.back()">
			<div id="top-nav-button-left">
				<%= image_tag("back3.png", :alt => "Message Button",  :class => "button-img") %>
			</div>
		</a>

		<a href="#">
			<input type="text" class="mainsearch" placeholder="Search..." >
		</a>


		<a href="">
			<div id="top-nav-button-right">
				<%= link_to image_tag("write3.png", :alt => "Message Button",  :class => "button-img"), new_post_path %>
			</div>
		</a>

	</header>	  
	  
  
  <!--Slide Out Menu -->
	  <nav>
		<ul>
			<li>
				<input type="text" class="navsearch" value="Search...">
			</li>
			
			<a href="/user/<%= current_user.name %>">
				<li class="user-prof-nav">
					<% if current_user.avatar.file? %>
					  <%= image_tag(current_user.avatar.url, :alt => "User Profile",  :class => "nav-prof-photo") %>
					<% else %>
					  <%= image_tag("profile.png", :alt => "Profile",  :class => "nav-prof-photo") %>
					<% end %>

					<p class="nav-prof-name"><%= current_user.name %></p>
				</li>
			</a>
			  
			<a href="<%= root_path %>">
				<li>				
					<%= image_tag("home.png", :alt => "Home",  :class => "slide-button") %>
					<p class="nav-prof-name">Home</p>
				</li>
			</a>				
			
			<a href="#">
				<li>
					<%= image_tag("local.png", :alt => "Local Area",  :class => "slide-button") %>
					<p class="nav-prof-name">Local Area</p>
				</li>
			</a>
			
			<a href="#">
				<li>
					<%= image_tag("message.png", :alt => "Messages",  :class => "slide-button") %>
					<p class="nav-prof-name">Messages</p>
				</li>
			</a>

			<a href="#">
				<li>
					<%= image_tag("faq.png", :alt => "FAQ",  :class => "slide-button") %>
					<p class="nav-prof-name">FAQ</p>
				</li>
			</a>

			<a href="#">
				<li>
					<%= image_tag("settings.png", :alt => "Settings",  :class => "slide-button") %>
					<p class="nav-prof-name">Settings</p>
			    </li>		  
			</a>			
		</ul>
		<div class="nav-bottom">

				<div class="logout-btn">
					<%= link_to "Sign out", destroy_user_session_path, :method => :delete %> 
				</div>
			
		</div>
	  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nomadr</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	<meta name="viewport" content="width=device-width, initial-scale = 1.0, maximum-scale=1.0, user-scalable=no"/>
	<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
	<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>

	<%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'slider', 'data-turbolinks-track' => true %>

	<%= csrf_meta_tags %>
</head>

<body data-no-turbolink="true"> <!-- Turn off turbo links (if turbolinks is on it removes page refresh, meaning naviation wil not work)-->

	<div id="container">
		<div id="contentLayer"></div>

			<%= render '/layouts/nav' %> <!-- Render top navigation, defined by _nav.html.erb -->


				<div id="content">

					<div class="notification"> 
						<p class="notice"><%= notice %></p> <!-- Signed in/ Out notification-->
			       		<p class="alert"><%= alert %></p> <!-- Slert notification -->
			       	</div>

				<%= yield %>


				</div>
			<%= render '/layouts/bottom' %> <!-- Render bottom navigation, defined by _nav.html.erb -->

	</div>
</body>
</html>

app/views/posts/_form.html.erb
<div class="post">
	<%= simple_form_for @post do |f| %> <!-- create a post form -->
		<%= f.input :title %> <!-- Add Title-->
		<%= f.input :description %> <!-- Add description-->
		<br/>
		<%= f.input :image %> <!-- Add image -->
		<br/>
		<%= f.button :submit %> <!-- Submit Form -->
	<% end %>

	<br/>
	<a href="javascript:history.back()">Cancel</a> <!-- Back Button -->
</div>

app/views/posts/edit.html.erb
<div class="post">
	<h1>Edit Your Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/explore.html.erb
<div class="post">

<h1>Locations Results</h1>
	  
		<form onsubmit="confirmInput()">
			Enter your Location: <input id="searchterm" type="text">
		</form>

		<button id="search">Search</button>
      
      <ul id="results">
        
      </ul>


		<script>

		// When the new button is clicked, don't reload the page, then run the runSearch function
		// passing in the location the user put in the text box
		$("#search").on('click', function(e){
			e.preventDefault();

		//store their input 
			var userLoc = $("#searchterm").val();

		//send it to the function with the call to foursquare 
			runSearch(userLoc);
		})


		function runSearch(userLoc){
			$("#results").html('');
			$.ajax({
				url: 'https://api.foursquare.com/v2/venues/search',
				data: {
					near: userLoc, // Uses the user's search query to pull relevant hostels from location
					limit: 10, //Limit's ammount to 10
					intent: 'browse',
					categoryId: '4bf58dd8d48988d1ee931735',
					client_id: '2YMWDLKHO03GQKJ0UDPSDZ5LJRKJEJNDZG1TXTGSAH3JMXUD',
					client_secret: 'M1DZ421SKKNYEQBK4A3KC1JRE4QR2SR0PYPVEBPMVBPWLA2P',
					v: 20151230,
					m: 'foursquare'
				}
			})

			.done(function(response){
				var hostels = response.response.venues;
				$.each(hostels, function(key, hostels){
					var hostelID = hostels.id;
					var name = hostels.name;
					var rating = hostels.rating;
					var address = hostels.location.formattedAddress;
					var checkin = hostels.stats.checkinsCount;

                    $("#results").append(
                    	"<ul data-hostel-id='" + hostelID + "' data-hostel-name='"+ name +"' data-address='" + address + "data-checkin'" + checkin + "' > " 

                    			
			                    	+ name + "<br>" //Displays returned hostels as list
			                    	+ address + "<br>"  
			                    	+ checkin + " People Checked In" + "<br>" + "<br>" 

			                    + "</ul>" 

                    	);

				})

			});
		}



		</script>

</div>

app/views/posts/index.html.erb
<div class="post">

	<p>	
		You aren't logged in
	</p>


			<%= link_to('Log In', new_user_session_path) %><br><br> <!-- Link to log in -->
			<%= link_to('Sign Up', new_user_registration_path) %> <!-- Link to Sign Up-->

</div>

app/views/posts/new.html.erb
<div class="post">
	<h1>Write A Post</h1>

	<%= render 'form' %> <!-- Render _form.html.erb -->
</div>

app/views/posts/profile.html.erb
<div class="user_prof_panel">
	<% @posts.first(1).each do |post| %> <!-- Shows posts, defined in posts_controller.rb -->
		<% if post.user.avatar.file? %>
		  <%= image_tag( post.user.avatar , :alt => "Profile",  :class => "user_photo") %> <!-- Post the User's profile photo -->
		<% else %>
		  <%= image_tag("profile.png", :alt => "Profile",  :class => "user_photo") %> <!-- If no profile photo, post default photo located in assets-->
		<% end %>
	<% end %>
	<h3><%= @username %></h3>
	<%= link_to "Edit Profile", edit_user_registration_path %> <!-- Edit Profile -->
</div>


<% @posts.each do |post| %>
	<div class="post">
		<% if post.user.avatar.file? %>
				<%= image_tag( post.user.avatar , :alt => "Profile",  :class => "post-prof-photo") %> <!-- Post the User's profile photo -->
			<% else %>
				<%= image_tag("profile.png", :alt => "Profile",  :class => "post-prof-photo") %> <!-- If no profile photo, post default photo located in assets-->
		<% end %>
		
			<p class="post-username"><%= post.user.name %></p> <!-- Post username -->

			<br>
		<p class="post-date">Posted <%= time_ago_in_words (post.created_at) %> ago</p> <!-- Post date of when posted -->

		
		<p><%= link_to post.title, post %></p>

			<% if post.image.file? %>
				<%= link_to (image_tag post.image.url, :class => "post-photo"), post %> <!-- Post photo attached-->
			<% else %>
						<!-- If no photo, show nothing -->
			<% end %>
		
		
		<div class= "text-truncate">
			<p class="post-text"><%= link_to post.description, post %></p> <!-- Show post description -->
		</div>

		<br>
			<p><%= post.comments.count %> Comments</p> <!-- Show how many comments -->
			<p><%= post.get_upvotes.size %> Likes</p> <!-- Show how many upvotes -->
			<p><%= post.get_downvotes.size %> Dislikes</p> <!-- Show how many downvotes -->
		<br>

		<div class="post-button-middle"><%= link_to "Like", like_post_path(post), :class => "like-btn", method: :get %></div> <!-- Like Post -->

		<div class="post-button"><%= link_to "Dislike", dislike_post_path(post), :class => "like-btn", method: :get %></div> <!-- Dislike Post-->

			<br>
	</div>
<% end %>

app/views/posts/show.html.erb
<div class="post">
	<% if @post.user.avatar.file? %>
			  <%= image_tag( @post.user.avatar , :alt => "Profile",  :class => "post-prof-photo") %> <!-- Post the User's profile photo -->
		<% else %>
			  <%= image_tag("profile.png", :alt => "Profile",  :class => "post-prof-photo") %> <!-- If no profile photo, post default photo located in assets-->
	<% end %>

	<a href="/user/<%= @post.user.name %>">
		<p class="post-username"><%= @post.user.name %></p>  <!-- Post username -->
	</a>
		<br>
	<p class="post-date">Posted <%= time_ago_in_words (@post.created_at) %> ago</p> <!-- Post date of when posted -->
	
	<p><%= @post.title %></p> <!-- Post Title-->

		<% if @post.image.file? %>
			<%= image_tag @post.image.url, :alt => "Post Image",  :class => "post-photo" %> <!-- Post photo attached-->
		<% else %>
						<!-- If no photo, show nothing -->
		<% end %>

		

	<p class="post-text"><%= @post.description %></p> <!-- Show post description -->

		<br>
			<p><%= @post.comments.count %> Comments</p> <!-- Show how many comments -->
			<p><%= @post.get_upvotes.size %> Likes</p> <!-- Show how many upvotes -->
			<p><%= @post.get_downvotes.size %> Dislikes</p> <!-- Show how many downvotes -->
		<br>

		<a href="#">
			<div class="post-button-middle"><%= link_to "Like", like_post_path(@post), method: :get %></div> <!-- Like Post -->
		</a>
		<a href="">
			<div class="post-button"><%= link_to "Dislike", dislike_post_path(@post), method: :get %></div> <!-- Dislike Post-->
		</a>
		<br>
			<%= link_to "Edit", edit_post_path(@post) %> <!-- Edit Post-->
			<br>
			
		<br>

		<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %> <!-- Delete Post-->
</div>

<div class="post">
	<h2><%= pluralize(@post.comments.count, "Comment") %></h2> <!-- Show ammount of comments, pluralize if more than 1-->

	
	<%= render 'comments/form' %> <!-- Render the comment form -->

		<% @comments.each do |comment| %>
			<div class="comment">
				<p class="username"><%= comment.user.name %></p> <!-- Comment Username-->
				<p class="content"><%= comment.content %></p> <!-- Comment post-->
				<p class="post-date">Posted <%= time_ago_in_words (comment.created_at) %> ago</p> <!-- Comment post date-->
			</div>
		<% end %>
						
</div>

app/views/posts/userindex.html.erb
	
  <!-- User Post -->
	<% @posts.each do |post| %> <!-- Shows posts, defined in posts_controller.rb -->
		<div class="post">
			<% if post.user.avatar.file? %>
				<%= image_tag( post.user.avatar , :alt => "Profile",  :class => "post-prof-photo") %> <!-- Post the User's profile photo -->
			<% else %>
				<%= image_tag("profile.png", :alt => "Profile",  :class => "post-prof-photo") %> <!-- If no profile photo, post default photo located in assets-->
			<% end %>


			<a href="/user/<%= post.user.name %>">
				<p class="post-username">
					<% if post.user.name? %> <!-- Post username -->
						<%= post.user.name %> 
					<% else %>
						User Deleted <!-- If no username, post "User Deleted"-->
				<% end %>
			</a>
				<br>
			<p class="post-date">Posted <%= time_ago_in_words (post.created_at) %> ago</p> <!-- Post date of when posted -->

			
			<p><%= link_to post.title, post %></p> <!-- Post Title-->

			<% if post.image.file? %>
				<%= link_to (image_tag post.image.url, :class => "post-photo"), post %> <!-- Post photo attached-->
			<% else %>
						<!-- If no photo, show nothing -->
			<% end %>
			
			
			<div class= "text-truncate">
				<p class="post-text"><%= link_to post.description, post %></p> <!-- Links to post page-->
			</div>

			<br>
				<p><%= post.comments.count %> Comments</p> <!-- Show how many comments -->
				<p><%= post.get_upvotes.size %> Likes</p> <!-- Show how many upvotes -->
				<p><%= post.get_downvotes.size %> Dislikes</p> <!-- Show how many downvotes -->
			<br>
		<a href="#">
			<div class="post-button-middle"><%= link_to "Like", like_post_path(post), method: :get %></div> <!-- Like Post -->
		</a>
		<a href="">
			<div class="post-button"><%= link_to "Dislike", dislike_post_path(post), method: :get %></div> <!-- Dislike Post-->
		</a>
				<br>
		</div>
	<% end %>